### PR TITLE
Use an auth token for extended ratelimit

### PR DESCRIPTION
**Pull request by amCap1712**
Daily jams are failing for users in production due to ratelimit errors. The intent is to pass troi's auth token to the patch in prod so that the ratelimit can be bypassed.

### CODE REVIEW

**Comment by amCap1712** [comment]
tested in prod. this still doesn't scale to all users.

**Comment by amCap1712** [comment]
There was a bug in getting the token due to which we never got the extended ratelimit earlier. fixed now.

**Comment by mayhem** [comment]
I'm not fond of having to pass around the auth token, but this works fine for now. Before too long I want to implement Patch Local Storage, so that auth keys, playlist names are whatever else that the entire pipeline might be interested in using is available to all elements without passing around so many things.

**Comment by amCap1712** [comment]
That Patch Local Storage sounds good to me.

**Pull request merged**
